#!/usr/bin/env bash
# Generate INDEX.md: a topic -> file map grouped by top-level category.
# Pure shell/awk, no extra deps, so CI can run it like the README tree.
# Label = first Markdown "# H1" in the file, else the filename.
# ponytail: H1-or-filename heuristic; switch to front-matter tags only if labels get noisy.
set -euo pipefail

cd "$(dirname "$0")"
OUT=INDEX.md

# Tracked + untracked-but-not-ignored files, so the index is correct before the
# new files are committed too. ponytail: one git call, respects .gitignore.
files() { git ls-files --cached --others --exclude-standard; }

label() { # $1 = path -> a human label
  if [[ "$1" == *.md ]]; then
    local h
    h="$(grep -m1 -E '^# ' "$1" 2>/dev/null | sed -E 's/^#[[:space:]]*//')"
    [ -n "$h" ] && { printf '%s' "$h"; return; }
  fi
  basename "$1"
}

{
  echo "# Index"
  echo
  echo "_Auto-generated by [gen-index.sh](gen-index.sh) — do not edit by hand._"
  echo
  echo "Fuzzy-search these from the terminal with [\`search.sh\`](search.sh)."
  echo
} >"$OUT"

# Top-level category dirs, alphabetical, skipping dotdirs.
# Skip non-snippet dirs (CI config, scratch plans).
for dir in $(files | awk -F/ 'NF>1{print $1}' | grep -vE '^\.|^plans$' | sort -u); do
  echo "## $dir" >>"$OUT"
  echo >>"$OUT"
  echo "| File | Topic |" >>"$OUT"
  echo "|---|---|" >>"$OUT"
  files | grep -E "^$dir/" | sort | while read -r f; do
    printf '| [%s](%s) | %s |\n' "$(basename "$f")" "$f" "$(label "$f")" >>"$OUT"
  done
  echo >>"$OUT"
done

echo "Wrote $OUT"
