# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dhwani_model.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dhwani_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64hwani_model.proto\x12\nwavservice\"8\n\nWavRequest\x12\x17\n\x0fwav_data_base64\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\"\x1d\n\x0bWavResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2O\n\x0cWavProcessor\x12?\n\nProcessWav\x12\x16.wavservice.WavRequest\x1a\x17.wavservice.WavResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dhwani_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAVREQUEST']._serialized_start=34
  _globals['_WAVREQUEST']._serialized_end=90
  _globals['_WAVRESPONSE']._serialized_start=92
  _globals['_WAVRESPONSE']._serialized_end=121
  _globals['_WAVPROCESSOR']._serialized_start=123
  _globals['_WAVPROCESSOR']._serialized_end=202
# @@protoc_insertion_point(module_scope)
